-- Adds weather / calendar columns to raw_demand (run once)
ALTER TABLE raw_demand
    ADD COLUMN IF NOT EXISTS hm DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ta DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS holiday_name VARCHAR(200),
    ADD COLUMN IF NOT EXISTS weekday SMALLINT,
    ADD COLUMN IF NOT EXISTS weekend SMALLINT,
    ADD COLUMN IF NOT EXISTS spring SMALLINT,
    ADD COLUMN IF NOT EXISTS summer SMALLINT,
    ADD COLUMN IF NOT EXISTS autoum SMALLINT,
    ADD COLUMN IF NOT EXISTS winter SMALLINT,
    ADD COLUMN IF NOT EXISTS is_holiday_dummies SMALLINT;

